### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [WasmEdge/www#13]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by nate-double-u** [comment]
<img width="935" alt="Screenshot 2022-11-22 at 11 00 42 AM" src="https://user-images.githubusercontent.com/4453979/203398942-0cff245a-05b5-485f-8bf9-8b1e460ce722.png">

test deploy: https://app.netlify.com/sites/wasmedge/deploys/637d1c790db3dc198fe4702f

Since the builds were failing i've gone ahead and made the change.

We should still make sure that we add folks from WasmEdge to the Netlify project so that you're able to make changes yourselves if needed.

**Comment by nate-double-u** [comment]
If no one on your team is able to access https://app.netlify.com/teams/cncf-projects/overview, please let me know and we can arrange to invite someone.

**Comment by hydai** [comment]
Hi @nate-double-u 
Could you please add me to the team? I think our members cannot access the team you mentioned.

**Comment by juntao** [comment]
My apologies. It seems that I have access. I have triggered a new build and deploy. It seems to be working now. :) Thank you.

**Comment by nate-double-u** [comment]
closing as complete, thanks everyone!
